package Interface;

import Processing.YahtzeeGame;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.border.LineBorder;

/**
 *
 @author Úlfur Alexander Einarsson, uae3@hi.is
 * 29/03 2015
 * 
 * Lýsing:
 * GameWindow inniheldur allar viðmótsbreytur leiksins.
 * Hnappa, textasvið með stöðu leiksins, myndir af teningum, 
 * og blað með reitum þar sem hægt er að skrá útkomur teningakasta.
 * Leyfir notanda að kasta teningum, hefja nýjan leik og fá leiðbeiningar 
 */

public class YahtzeeWindow extends javax.swing.JFrame 
{
    // boolean breyta sem segir til hvort tiltekinn teningur sé valinn
    private Boolean notPicked;
     
    // Smiður frumstillir útlit leiksins    
    public YahtzeeWindow() 
    {
        initComponents();
        
        this.getContentPane().setBackground(new Color(204,255,153));
    }
    
    // Afmerkir teningana sem er búið að velja
    public static void resetMarkedDice() {
        dicePic1.setBorder(null);
        dicePic2.setBorder(null);
        dicePic3.setBorder(null);
        dicePic4.setBorder(null);
        dicePic5.setBorder(null);
    }
    
    // Endurstillir myndirnar af teningum í "1"
    public static void resetDicePics() {
        ImageIcon ni = new ImageIcon(YahtzeeWindow.class.getResource("/Interface/dice1.png"));
        dicePic1.setIcon(ni);
        dicePic2.setIcon(ni);
        dicePic3.setIcon(ni);
        dicePic4.setIcon(ni);
        dicePic5.setIcon(ni);   
    }
    
    // Setur kassa í kringum tening sem er búið að velja, eða fjarlægir
    // kassann ef það er kassi utan um teninginn nú þegar
    private void markDice(JLabel thisDice) 
    {  
        if(thisDice.getBorder()==null) {
            notPicked = true;
            thisDice.setBorder(new LineBorder(new Color(153,0,51),1)); }
        else {
            notPicked = false;
            thisDice.setBorder(null);}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogHelp = new javax.swing.JDialog();
        hjalpTexti = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        yatziBlad = new javax.swing.JPanel();
        onesBtn = new javax.swing.JButton();
        ones = new javax.swing.JFormattedTextField();
        twosBtn = new javax.swing.JButton();
        twos = new javax.swing.JFormattedTextField();
        threesBtn = new javax.swing.JButton();
        threes = new javax.swing.JFormattedTextField();
        foursBtn = new javax.swing.JButton();
        fours = new javax.swing.JFormattedTextField();
        fivesBtn = new javax.swing.JButton();
        fives = new javax.swing.JFormattedTextField();
        sixesBtn = new javax.swing.JButton();
        sixes = new javax.swing.JFormattedTextField();
        same3Btn = new javax.swing.JButton();
        same3 = new javax.swing.JFormattedTextField();
        same4Btn = new javax.swing.JButton();
        same4 = new javax.swing.JFormattedTextField();
        smallstraightBtn = new javax.swing.JButton();
        smallstraight = new javax.swing.JFormattedTextField();
        bigstraightBtn = new javax.swing.JButton();
        bigstraight = new javax.swing.JFormattedTextField();
        chanceBtn = new javax.swing.JButton();
        chance = new javax.swing.JFormattedTextField();
        same5Btn = new javax.swing.JButton();
        same5 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JLabel();
        nyrleikurBtn = new javax.swing.JButton();
        throwBtn = new javax.swing.JButton();
        normalDiceBox = new javax.swing.JPanel();
        dicePic1 = new javax.swing.JLabel();
        dicePic2 = new javax.swing.JLabel();
        dicePic3 = new javax.swing.JLabel();
        dicePic4 = new javax.swing.JLabel();
        dicePic5 = new javax.swing.JLabel();
        helpBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        roundsCountLbl = new javax.swing.JLabel();
        gameOverTxt = new javax.swing.JLabel();

        dialogHelp.setTitle("Hjálp");
        dialogHelp.setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("MS Gothic", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Velkomin í Yahtzee leikinn\n\nSmelltu á \"Kasta teningum\" og \nýttu teningana sem að þú villt \ntaka frá.\nÞú getur kastað þrisvar í hvert\nskipti.\nSkrifaðu á blaðið  hvernig þú \nvillt skrá útkomuna sem þú \nfærð í hverju kassti.\n");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setFocusable(false);
        hjalpTexti.setViewportView(jTextArea1);

        javax.swing.GroupLayout dialogHelpLayout = new javax.swing.GroupLayout(dialogHelp.getContentPane());
        dialogHelp.getContentPane().setLayout(dialogHelpLayout);
        dialogHelpLayout.setHorizontalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHelpLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(hjalpTexti, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        dialogHelpLayout.setVerticalGroup(
            dialogHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogHelpLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(hjalpTexti, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Yahtzee leikur");
        setBackground(new java.awt.Color(204, 255, 153));
        setBounds(new java.awt.Rectangle(0, 0, 500, 500));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(500, 500));

        yatziBlad.setBackground(new java.awt.Color(255, 255, 255));
        yatziBlad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        yatziBlad.setAlignmentX(4.0F);
        yatziBlad.setAlignmentY(4.0F);
        yatziBlad.setLayout(new java.awt.GridLayout(13, 2, 0, -1));

        onesBtn.setBackground(new java.awt.Color(255, 255, 255));
        onesBtn.setForeground(new java.awt.Color(0, 51, 0));
        onesBtn.setText("Ásar");
        onesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        onesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onesBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(onesBtn);

        ones.setEditable(false);
        ones.setBackground(new java.awt.Color(255, 255, 255));
        ones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ones.setColumns(1);
        ones.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        ones.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ones.setText("0");
        yatziBlad.add(ones);

        twosBtn.setBackground(new java.awt.Color(255, 255, 255));
        twosBtn.setForeground(new java.awt.Color(0, 51, 0));
        twosBtn.setText("Tvistar");
        twosBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        twosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twosBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(twosBtn);

        twos.setEditable(false);
        twos.setBackground(new java.awt.Color(255, 255, 255));
        twos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        twos.setColumns(2);
        twos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        twos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        twos.setText("0");
        yatziBlad.add(twos);

        threesBtn.setBackground(new java.awt.Color(255, 255, 255));
        threesBtn.setForeground(new java.awt.Color(0, 51, 0));
        threesBtn.setText("Þristar");
        threesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        threesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threesBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(threesBtn);

        threes.setEditable(false);
        threes.setBackground(new java.awt.Color(255, 255, 255));
        threes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        threes.setColumns(2);
        threes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        threes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        threes.setText("0");
        yatziBlad.add(threes);

        foursBtn.setBackground(new java.awt.Color(255, 255, 255));
        foursBtn.setForeground(new java.awt.Color(0, 51, 0));
        foursBtn.setText("Fjarkar");
        foursBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        foursBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foursBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(foursBtn);

        fours.setEditable(false);
        fours.setBackground(new java.awt.Color(255, 255, 255));
        fours.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fours.setColumns(2);
        fours.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fours.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fours.setText("0");
        yatziBlad.add(fours);

        fivesBtn.setBackground(new java.awt.Color(255, 255, 255));
        fivesBtn.setForeground(new java.awt.Color(0, 51, 0));
        fivesBtn.setText("Fimmur");
        fivesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fivesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fivesBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(fivesBtn);

        fives.setEditable(false);
        fives.setBackground(new java.awt.Color(255, 255, 255));
        fives.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fives.setColumns(2);
        fives.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        fives.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fives.setText("0");
        yatziBlad.add(fives);

        sixesBtn.setBackground(new java.awt.Color(255, 255, 255));
        sixesBtn.setForeground(new java.awt.Color(0, 51, 0));
        sixesBtn.setText("Sexur");
        sixesBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        sixesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixesBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(sixesBtn);

        sixes.setEditable(false);
        sixes.setBackground(new java.awt.Color(255, 255, 255));
        sixes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sixes.setColumns(2);
        sixes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        sixes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        sixes.setText("0");
        yatziBlad.add(sixes);

        same3Btn.setBackground(new java.awt.Color(255, 255, 255));
        same3Btn.setForeground(new java.awt.Color(0, 51, 0));
        same3Btn.setText("3 eins");
        same3Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        same3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                same3BtnActionPerformed(evt);
            }
        });
        yatziBlad.add(same3Btn);

        same3.setEditable(false);
        same3.setBackground(new java.awt.Color(255, 255, 255));
        same3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        same3.setColumns(2);
        same3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        same3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        same3.setText("0");
        yatziBlad.add(same3);

        same4Btn.setBackground(new java.awt.Color(255, 255, 255));
        same4Btn.setForeground(new java.awt.Color(0, 51, 0));
        same4Btn.setText("4 eins");
        same4Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        same4Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                same4BtnActionPerformed(evt);
            }
        });
        yatziBlad.add(same4Btn);

        same4.setEditable(false);
        same4.setBackground(new java.awt.Color(255, 255, 255));
        same4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        same4.setColumns(2);
        same4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        same4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        same4.setText("0");
        yatziBlad.add(same4);

        smallstraightBtn.setBackground(new java.awt.Color(255, 255, 255));
        smallstraightBtn.setForeground(new java.awt.Color(0, 51, 0));
        smallstraightBtn.setText("Lítil röð");
        smallstraightBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        smallstraightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smallstraightBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(smallstraightBtn);

        smallstraight.setEditable(false);
        smallstraight.setBackground(new java.awt.Color(255, 255, 255));
        smallstraight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        smallstraight.setColumns(2);
        smallstraight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        smallstraight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        smallstraight.setText("0");
        yatziBlad.add(smallstraight);

        bigstraightBtn.setBackground(new java.awt.Color(255, 255, 255));
        bigstraightBtn.setForeground(new java.awt.Color(0, 51, 0));
        bigstraightBtn.setText("Stór röð");
        bigstraightBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bigstraightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigstraightBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(bigstraightBtn);

        bigstraight.setEditable(false);
        bigstraight.setBackground(new java.awt.Color(255, 255, 255));
        bigstraight.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bigstraight.setColumns(2);
        bigstraight.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        bigstraight.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bigstraight.setText("0");
        yatziBlad.add(bigstraight);

        chanceBtn.setBackground(new java.awt.Color(255, 255, 255));
        chanceBtn.setForeground(new java.awt.Color(0, 51, 0));
        chanceBtn.setText("Taka sénsinn");
        chanceBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chanceBtnActionPerformed(evt);
            }
        });
        yatziBlad.add(chanceBtn);

        chance.setEditable(false);
        chance.setBackground(new java.awt.Color(255, 255, 255));
        chance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chance.setColumns(2);
        chance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        chance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chance.setText("0");
        yatziBlad.add(chance);

        same5Btn.setBackground(new java.awt.Color(255, 255, 255));
        same5Btn.setForeground(new java.awt.Color(0, 51, 0));
        same5Btn.setText("Yahtzee");
        same5Btn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        same5Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                same5BtnActionPerformed(evt);
            }
        });
        yatziBlad.add(same5Btn);

        same5.setEditable(false);
        same5.setBackground(new java.awt.Color(255, 255, 255));
        same5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        same5.setColumns(2);
        same5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        same5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        same5.setText("0");
        yatziBlad.add(same5);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Samtals:");
        yatziBlad.add(jLabel9);

        totalTxt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        totalTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalTxt.setText("0");
        yatziBlad.add(totalTxt);

        nyrleikurBtn.setText("Nýr Leikur");
        nyrleikurBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyrleikurBtnActionPerformed(evt);
            }
        });

        throwBtn.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        throwBtn.setText("Kasta teningum");
        throwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                throwBtnActionPerformed(evt);
            }
        });

        normalDiceBox.setAlignmentX(1.0F);
        normalDiceBox.setAlignmentY(1.0F);
        normalDiceBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        normalDiceBox.setOpaque(false);
        normalDiceBox.setLayout(new java.awt.GridLayout(1, 0));

        dicePic1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dicePic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dicePic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dice1.png"))); // NOI18N
        dicePic1.setToolTipText("");
        dicePic1.setMaximumSize(new java.awt.Dimension(50, 50));
        dicePic1.setMinimumSize(new java.awt.Dimension(50, 50));
        dicePic1.setName("d1"); // NOI18N
        dicePic1.setPreferredSize(new java.awt.Dimension(55, 55));
        dicePic1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dicePic5MouseClicked(evt);
            }
        });
        normalDiceBox.add(dicePic1);

        dicePic2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dicePic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dicePic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dice1.png"))); // NOI18N
        dicePic2.setToolTipText("");
        dicePic2.setName("d2"); // NOI18N
        dicePic2.setPreferredSize(new java.awt.Dimension(55, 55));
        dicePic2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dicePic5MouseClicked(evt);
            }
        });
        normalDiceBox.add(dicePic2);

        dicePic3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dicePic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dicePic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dice1.png"))); // NOI18N
        dicePic3.setName("d3"); // NOI18N
        dicePic3.setPreferredSize(new java.awt.Dimension(55, 55));
        dicePic3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dicePic5MouseClicked(evt);
            }
        });
        normalDiceBox.add(dicePic3);

        dicePic4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dicePic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dicePic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dice1.png"))); // NOI18N
        dicePic4.setName("d4"); // NOI18N
        dicePic4.setPreferredSize(new java.awt.Dimension(55, 55));
        dicePic4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dicePic5MouseClicked(evt);
            }
        });
        normalDiceBox.add(dicePic4);

        dicePic5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dicePic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dicePic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/dice1.png"))); // NOI18N
        dicePic5.setName("d5"); // NOI18N
        dicePic5.setPreferredSize(new java.awt.Dimension(55, 55));
        dicePic5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dicePic5MouseClicked(evt);
            }
        });
        normalDiceBox.add(dicePic5);

        helpBtn.setText("Leiðbeiningar");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Umferð:");

        roundsCountLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        roundsCountLbl.setText("--");

        gameOverTxt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gameOverTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gameOverTxt.setText("Til hamingju! Þú fékkst 120 stig!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(throwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(normalDiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roundsCountLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(gameOverTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(yatziBlad, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nyrleikurBtn)
                .addGap(49, 49, 49)
                .addComponent(helpBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(throwBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(roundsCountLbl)))
                        .addGap(18, 18, 18)
                        .addComponent(normalDiceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(gameOverTxt))
                    .addComponent(yatziBlad, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nyrleikurBtn)
                    .addComponent(helpBtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Atburðahandler fyrir "Nýr leikur" hnappinn
    // Keyrir fallið nyrLeikur() úr klasanum YahtzeeGame
    // @param evt : atburður fyrir hnappinn
    private void nyrleikurBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyrleikurBtnActionPerformed
        
        YahtzeeGame.newGame();
    }//GEN-LAST:event_nyrleikurBtnActionPerformed
    
    // Atburðahandler fyrir "Kasta teningum" hnappinn
    // Athugar og breytir ástandi count og roundsCount
    // Breytir ástandi throwBtn og valdra teninga
    // Keyrir fallið newThrow() úr klasanum YahtzeeGame  sem gefur teningum 
    // ný gildi
    // @param evt : atburður fyrir hnappinn
    private void throwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_throwBtnActionPerformed
        
        if (YahtzeeGame.count == 2)
        {  
            throwBtn.setLabel("Kasta nýrri umferð");
            throwBtn.setEnabled(false);
            YahtzeeGame.count=-1;
        }
        else if (YahtzeeGame.count == 0)
        {
            throwBtn.setLabel("Kasta teningum");
            YahtzeeGame.dicePickedNameList.clear();
            resetMarkedDice();
            YahtzeeGame.roundsCount++;
            roundsCountLbl.setText(Integer.toString(YahtzeeGame.roundsCount));
        }
        
        YahtzeeGame.newThrow(dicePic1,dicePic2,dicePic3,dicePic4,dicePic5);
    }//GEN-LAST:event_throwBtnActionPerformed
    
    // Atburðahandler fyrir myndirnar af teningunum
    // Merkir teninginn eða afmerkir hann
    // Uppfærir dicePickedList og dicePickedNameList í YahtzeeGame klasanum
    // með gildi teningsins
    // @param evt : atburður fyrir hnappinn
    private void dicePic5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dicePic5MouseClicked
        
        javax.swing.JLabel thisDice = (javax.swing.JLabel)evt.getSource();
        
        markDice(thisDice);
        
        if(notPicked==true) {
            YahtzeeGame.dicePickedNameList.add(thisDice.getName());
            YahtzeeGame.dicePickedList.add(thisDice.getToolTipText());
        } else {
            YahtzeeGame.dicePickedNameList.remove(thisDice.getName());
            YahtzeeGame.dicePickedList.remove(thisDice.getToolTipText());
        }
        
    }//GEN-LAST:event_dicePic5MouseClicked
    // Atburðahandlerar fyrir "Hjálp" hnappin sem opnar glugga með leiðbeiningum
    // @param evt : atburður fyrir hnappinn
    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        
        dialogHelp.setBounds(20, 20, 270, 210);
        dialogHelp.show();
    }//GEN-LAST:event_helpBtnActionPerformed
    
    // Atburðahandlerar fyrir hnappana sem skrá í tölur í reitina 
    // Keyrir fallið calculateDice(int, jTextfield) í YahtzeeGame klasanum
    // Aðferðirnar hér á eftir eru eins fyrir hina hnappana: tvista, þrista,
    // 4 eins, yatzi o.s.frv. 
    // @param evt : atburður fyrir hnappinn 
    private void onesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onesBtnActionPerformed
        
        YahtzeeGame.calculateDice(1, ones);
    }//GEN-LAST:event_onesBtnActionPerformed

    private void twosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twosBtnActionPerformed
        
        YahtzeeGame.calculateDice(2, twos);
    }//GEN-LAST:event_twosBtnActionPerformed

    private void foursBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foursBtnActionPerformed
        
        YahtzeeGame.calculateDice(4, fours);
    }//GEN-LAST:event_foursBtnActionPerformed

    private void threesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threesBtnActionPerformed
        
        YahtzeeGame.calculateDice(3, threes);
    }//GEN-LAST:event_threesBtnActionPerformed

    private void fivesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fivesBtnActionPerformed
        
        YahtzeeGame.calculateDice(5, fives);
    }//GEN-LAST:event_fivesBtnActionPerformed

    private void sixesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixesBtnActionPerformed
        
        YahtzeeGame.calculateDice(6, sixes);
    }//GEN-LAST:event_sixesBtnActionPerformed

    private void same3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_same3BtnActionPerformed
        
        YahtzeeGame.calculateDice(333, same3);
    }//GEN-LAST:event_same3BtnActionPerformed

    private void same4BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_same4BtnActionPerformed
        
        YahtzeeGame.calculateDice(4444, same4);
    }//GEN-LAST:event_same4BtnActionPerformed

    private void same5BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_same5BtnActionPerformed
        
        YahtzeeGame.calculateDice(55555, same5);
    }//GEN-LAST:event_same5BtnActionPerformed

    private void chanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chanceBtnActionPerformed
        
        YahtzeeGame.calculateDice(666, chance);
    }//GEN-LAST:event_chanceBtnActionPerformed

    private void smallstraightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smallstraightBtnActionPerformed
        
        YahtzeeGame.calculateDice(12345, smallstraight);
    }//GEN-LAST:event_smallstraightBtnActionPerformed

    private void bigstraightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigstraightBtnActionPerformed
        
        YahtzeeGame.calculateDice(23456, bigstraight);
    }//GEN-LAST:event_bigstraightBtnActionPerformed

      
    
    /**
     * @param args the command line arguments
     */
    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YahtzeeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YahtzeeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YahtzeeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YahtzeeWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YahtzeeWindow().setVisible(true);
            }
        });
    }

    // Innbyggt fall sem býr til viðmótsbreytunar.
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JFormattedTextField bigstraight;
    public static javax.swing.JButton bigstraightBtn;
    public static javax.swing.JFormattedTextField chance;
    public static javax.swing.JButton chanceBtn;
    private javax.swing.JDialog dialogHelp;
    public static javax.swing.JLabel dicePic1;
    public static javax.swing.JLabel dicePic2;
    public static javax.swing.JLabel dicePic3;
    public static javax.swing.JLabel dicePic4;
    public static javax.swing.JLabel dicePic5;
    public static javax.swing.JFormattedTextField fives;
    public static javax.swing.JButton fivesBtn;
    public static javax.swing.JFormattedTextField fours;
    public static javax.swing.JButton foursBtn;
    public static javax.swing.JLabel gameOverTxt;
    private javax.swing.JButton helpBtn;
    private javax.swing.JScrollPane hjalpTexti;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel normalDiceBox;
    private javax.swing.JButton nyrleikurBtn;
    public static javax.swing.JFormattedTextField ones;
    public static javax.swing.JButton onesBtn;
    public static javax.swing.JLabel roundsCountLbl;
    public static javax.swing.JFormattedTextField same3;
    public static javax.swing.JButton same3Btn;
    public static javax.swing.JFormattedTextField same4;
    public static javax.swing.JButton same4Btn;
    public static javax.swing.JFormattedTextField same5;
    public static javax.swing.JButton same5Btn;
    public static javax.swing.JFormattedTextField sixes;
    public static javax.swing.JButton sixesBtn;
    public static javax.swing.JFormattedTextField smallstraight;
    public static javax.swing.JButton smallstraightBtn;
    public static javax.swing.JFormattedTextField threes;
    public static javax.swing.JButton threesBtn;
    public static javax.swing.JButton throwBtn;
    public static javax.swing.JLabel totalTxt;
    public static javax.swing.JFormattedTextField twos;
    public static javax.swing.JButton twosBtn;
    private javax.swing.JPanel yatziBlad;
    // End of variables declaration//GEN-END:variables
}
